#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Household;
    
    #line 6 "..\..\Views\Home\Index.cshtml"
    using Household.Controllers;
    
    #line default
    #line hidden
    
    #line 1 "..\..\Views\Home\Index.cshtml"
    using Household.Localisation.Common;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Views\Home\Index.cshtml"
    using Household.Localisation.Main;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Views\Home\Index.cshtml"
    using Household.Localisation.Main.Finance;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Views\Home\Index.cshtml"
    using Household.Localisation.Main.Work;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Views\Home\Index.cshtml"
    using Household.MvcExtensions;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Home/Index.cshtml")]
    public partial class _Views_Home_Index_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Home_Index_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\n");

            
            #line 8 "..\..\Views\Home\Index.cshtml"
  
	ViewBag.Title = GeneralText.Home;

            
            #line default
            #line hidden
WriteLiteral("\n\n<div");

WriteLiteral(" class=\"jumbotron\"");

WriteLiteral(">\n\t<h1>");

            
            #line 13 "..\..\Views\Home\Index.cshtml"
   Write(GeneralText.Household);

            
            #line default
            #line hidden
WriteLiteral("</h1>\n\t<p");

WriteLiteral(" class=\"lead\"");

WriteLiteral(">");

            
            #line 14 "..\..\Views\Home\Index.cshtml"
               Write(GeneralText.WelcomeToOurHouseholdManagementSystem);

            
            #line default
            #line hidden
WriteLiteral("</p>\n</div>\n\n<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\n\t<div");

WriteLiteral(" class=\"col-sm-6\"");

WriteLiteral(">\n\t\t<div");

WriteLiteral(" class=\"panel-finance panel-main-clickable\"");

WriteAttribute("onclick", Tuple.Create(" onclick=\"", 485), Tuple.Create("\"", 570)
, Tuple.Create(Tuple.Create("", 495), Tuple.Create("document.location", 495), true)
, Tuple.Create(Tuple.Create(" ", 512), Tuple.Create("=", 513), true)
, Tuple.Create(Tuple.Create(" ", 514), Tuple.Create("\'", 515), true)
            
            #line 19 "..\..\Views\Home\Index.cshtml"
       , Tuple.Create(Tuple.Create("", 516), Tuple.Create<System.Object, System.Int32>(Url.ActionFinance(nameof(FinanceController.Finance))
            
            #line default
            #line hidden
, 516), false)
, Tuple.Create(Tuple.Create("", 569), Tuple.Create("\'", 569), true)
);

WriteLiteral(">\n\t\t\t<div>\n\t\t\t\t<h2>");

            
            #line 21 "..\..\Views\Home\Index.cshtml"
               Write(FinanceText.Finance);

            
            #line default
            #line hidden
WriteLiteral("</h2>\n\t\t\t\t<p>");

            
            #line 22 "..\..\Views\Home\Index.cshtml"
              Write(FinanceText.ExpensesPurchasesAndMonthlyBills);

            
            #line default
            #line hidden
WriteLiteral("</p>\n\t\t\t</div>\n\t\t</div>\n\t</div>\n\t<div");

WriteLiteral(" class=\"col-sm-6\"");

WriteLiteral(">\n\t\t<div");

WriteLiteral(" class=\"panel-work panel-main-clickable\"");

WriteAttribute("onclick", Tuple.Create(" onclick=\"", 770), Tuple.Create("\"", 847)
, Tuple.Create(Tuple.Create("", 780), Tuple.Create("document.location", 780), true)
, Tuple.Create(Tuple.Create(" ", 797), Tuple.Create("=", 798), true)
, Tuple.Create(Tuple.Create(" ", 799), Tuple.Create("\'", 800), true)
            
            #line 27 "..\..\Views\Home\Index.cshtml"
    , Tuple.Create(Tuple.Create("", 801), Tuple.Create<System.Object, System.Int32>(Url.ActionWork(nameof(WorkController.Work))
            
            #line default
            #line hidden
, 801), false)
, Tuple.Create(Tuple.Create("", 845), Tuple.Create("\';", 845), true)
);

WriteLiteral(">\n\t\t\t<div>\n\t\t\t\t<h2>");

            
            #line 29 "..\..\Views\Home\Index.cshtml"
               Write(WorkText.Work);

            
            #line default
            #line hidden
WriteLiteral("</h2>\n\t\t\t\t<p>");

            
            #line 30 "..\..\Views\Home\Index.cshtml"
              Write(WorkText.ManageYourWorkingHours);

            
            #line default
            #line hidden
WriteLiteral("</p>\n\t\t\t</div>\n\t\t</div>\n\t</div>\n\t<div");

WriteLiteral(" class=\"col-sm-6\"");

WriteLiteral(">\n\t\t<div");

WriteLiteral(" class=\"panel-homeHDD panel-main-clickable\"");

WriteAttribute("onclick", Tuple.Create(" onclick=\"", 1031), Tuple.Create("\"", 1117)
, Tuple.Create(Tuple.Create("", 1041), Tuple.Create("document.location", 1041), true)
, Tuple.Create(Tuple.Create(" ", 1058), Tuple.Create("=", 1059), true)
, Tuple.Create(Tuple.Create(" ", 1060), Tuple.Create("\'", 1061), true)
            
            #line 35 "..\..\Views\Home\Index.cshtml"
      , Tuple.Create(Tuple.Create("", 1062), Tuple.Create<System.Object, System.Int32>(Url.ActionHomeHDD(nameof(HomeHDDController.HomeHDD))
            
            #line default
            #line hidden
, 1062), false)
, Tuple.Create(Tuple.Create("", 1115), Tuple.Create("\';", 1115), true)
);

WriteLiteral(">\n\t\t\t<div>\n\t\t\t\t<h2>");

            
            #line 37 "..\..\Views\Home\Index.cshtml"
               Write(HomeHDDText.HomeHDD);

            
            #line default
            #line hidden
WriteLiteral("</h2>\n\t\t\t\t<p>");

            
            #line 38 "..\..\Views\Home\Index.cshtml"
              Write(HomeHDDText.ComeOnInAndManageYourDocumentsAndPictures);

            
            #line default
            #line hidden
WriteLiteral("</p>\n\t\t\t</div>\n\t\t</div>\n\t</div>\n\t<div");

WriteLiteral(" class=\"col-sm-6\"");

WriteLiteral(">\n\t\t<div");

WriteLiteral(" class=\"panel-serverManager panel-main-clickable\"");

WriteAttribute("onclick", Tuple.Create(" onclick=\"", 1335), Tuple.Create("\"", 1438)
, Tuple.Create(Tuple.Create("", 1345), Tuple.Create("document.location", 1345), true)
, Tuple.Create(Tuple.Create(" ", 1362), Tuple.Create("=", 1363), true)
, Tuple.Create(Tuple.Create(" ", 1364), Tuple.Create("\'", 1365), true)
            
            #line 43 "..\..\Views\Home\Index.cshtml"
            , Tuple.Create(Tuple.Create("", 1366), Tuple.Create<System.Object, System.Int32>(Url.ActionServerManager(nameof(ServerManagerController.ServerManager))
            
            #line default
            #line hidden
, 1366), false)
, Tuple.Create(Tuple.Create("", 1437), Tuple.Create("\'", 1437), true)
);

WriteLiteral(">\n\t\t\t<div>\n\t\t\t\t<h2>");

            
            #line 45 "..\..\Views\Home\Index.cshtml"
               Write(ServerManagerText.ServerManager);

            
            #line default
            #line hidden
WriteLiteral("</h2>\n\t\t\t\t<p>");

            
            #line 46 "..\..\Views\Home\Index.cshtml"
              Write(ServerManagerText.CheckOutTheServerAndLookWhatIsGgoingOnInTheWorld);

            
            #line default
            #line hidden
WriteLiteral("</p>\n\t\t\t</div>\n\t\t</div>\n\t</div>\n</div>\n");

DefineSection("scripts", () => {

WriteLiteral("\n");

WriteLiteral("\t");

            
            #line 52 "..\..\Views\Home\Index.cshtml"
Write(Scripts.Render("~/bundles/Helpers"));

            
            #line default
            #line hidden
WriteLiteral("\n");

});

        }
    }
}
#pragma warning restore 1591
