// <auto-generated />
namespace Household.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ForeignKey_Purchase : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ForeignKey_Purchase));
        
        string IMigrationMetadata.Id
        {
            get { return "201606070835435_ForeignKey_Purchase"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
